config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'homes#index'
  get 'homes/show_asigs'
  get 'homes/show'
  resources :submits
  resources :searches
  devise_for :users, controllers: {
    sessions: 'users/sessions'}
  resources :assignments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/submit.rb
class Submit < ApplicationRecord
  belongs_to :user
  belongs_to :assignment
end

app/controllers/submits_controller.rb
class SubmitsController < ApplicationController
  before_action :set_submit, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  def index
    @submits = Submit.all
  end

  # GET /submits/1
  # GET /submits/1.json
  def show
  end

  # GET /submits/new
  def new
    @submit = current_user.submits.build
    @title = params[:title]
    @asig_id = params[ :asig_id]
     
  end

  # GET /submits/1/edit
  def edit
  end

  # POST /submits
  # POST /submits.json
  def create
    @submit = current_user.submits.build(submit_params)

    respond_to do |format|
      if @submit.save
        format.html { redirect_to root_path, notice: 'Submit was successfully created.' }
        format.json { render :show, status: :created, location: @submit }
      else
        format.html { render :new }
        format.json { render json: @submit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submits/1
  # PATCH/PUT /submits/1.json
  def update
    respond_to do |format|
      if @submit.update(submit_params)
        format.html { redirect_to @submit, notice: 'Submit was successfully updated.' }
        format.json { render :show, status: :ok, location: @submit }
      else
        format.html { render :edit }
        format.json { render json: @submit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submits/1
  # DELETE /submits/1.json
  def destroy
    @submit.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Submit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submit
      @submit = Submit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submit_params
      params.require(:submit).permit(:link, :user_id, :assignment_id)
    end
end

app/helpers/submits_helper.rb
module SubmitsHelper
end

app/views/submits/_form.html.erb
<body class="body1">

<%= form_with(model: submit, local: true) do |form| %>
  <% if submit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(submit.errors.count, "error") %> prohibited this submit from being saved:</h2>

      <ul>
      <% submit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  

  
<center><fieldset style="width:60%;background:#e9ecef;position:relative;top:-40px;"><legend>///////</legend>

 <div class="form-group row">
    <%= form.label :assignment_id ,class:'col-2 col-form-label' %>
                <div class="col-9" >

    <%= form.number_field :assignment_id, :value => @asig_id, readonly: true ,class:'form-control' %>
  </div>
  </div>
 <div class="form-group row">
    <%= form.label :assignment_title ,class:'col-2 col-form-label' %>
                    <div class="col-9" >

    <%= form.text_field :title, :value => @title, readonly: true ,class:'form-control' %>
  </div>
</div>
 <div class="form-group row">
    <%= form.label :link ,class:'col-2 col-form-label'%>
                        <div class="col-9" >

    <%= form.url_field :link ,class:'form-control' %>
  </div>
  </div>

  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</fieldset>
</center>
</body>

app/views/submits/edit.html.erb
<h1>Editing Submit</h1>

<%= render 'form', submit: @submit %>

<%= link_to 'Show', @submit %> |
<%= link_to 'Back', submits_path %>

app/views/submits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Submits</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Link</th>
      <th>User</th>
      <th>Assignment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @submits.each do |submit| %>
      <tr>
        <td><%= submit.link %></td>
        <td><%= submit.user %></td>
        <td><%= submit.assignment %></td>
        <td><%= link_to 'Show', submit %></td>
        <td><%= link_to 'Edit', edit_submit_path(submit) %></td>
        <td><%= link_to 'Destroy', submit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Submit', new_submit_path %>

app/views/submits/new.html.erb
<h1>New Submit</h1>

<%= render 'form', submit: @submit %>

<%= link_to 'Back', root_path %>

app/views/submits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @submit.link %>
</p>

<p>
  <strong>User:</strong>
  <%= @submit.user %>
</p>

<p>
  <strong>Assignment:</strong>
  <%= @submit.assignment %>
</p>

<%= link_to 'Edit', edit_submit_path(@submit) %> |
<%= link_to 'Back', submits_path %>