config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'homes#index'
  get 'homes/show_asigs'
  get 'homes/show'
  resources :submits
  resources :searches
  devise_for :users, controllers: {
    sessions: 'users/sessions'}
  resources :assignments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/search.rb
class Search < ApplicationRecord
belongs_to :level, class_name: "level", foreign_key: "level_id"
    def find_assignments
        assignments = Assignment.order(:title)
        assignments = Assignment.where("title like ?", "%#{ keywords}%" ) if keywords.present?
        assignments = Assignment.where(title: title) if title.present?
        assignments = Assignment.where(level_id: level_id) if level_id.present?
        assignments = Assignment.where("deadline <= ?", min_date) if min_date.present?
        assignments = Assignment.where("deadline >= ?", max_date) if max_date.present?
        assignments
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

    def new

        @levels = Level.all.collect { |m| [m.name, m.id] }
        @search = Search.new
        
    end
    def create

        @search = Search.create(search_params)
        redirect_to @search
    end
    def show
        @assignment = Assignment.all
           @search = Search.find(params[:id])
    end

    def search_params
        params.require(:search).permit(:keywords, :title, :min_date,  :level_id, :max_date,)
      end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/new.html.erb
<%= form_for @search do  |f|%>

<div class="field">
<%= f.label  :keywords  %><br />


<%=f.text_field  :keywords%>
</div>
<div class="field">
<%= f.label  :title  %><br />
<%=f.text_field  :title%>
</div>





<div class="field">
<%= f.label  :level_id %><br />


<%=f.collection_select :level_id,  Level.order(:name), :id, :name, include_blank: true  %>
</div>


<div class="field">
<%= f.label :min_date, "date range" %>

<%=f.date_field :min_date %><br />
<%=f.date_field :max_date %>
</div>

<%= f.submit "search"%>
<%end %>

app/views/searches/show.html.erb
p id="notice"><%= notice %></p>

<p>


<%@search.find_assignments.each do |c|%>
 

<p>
  <strong>Title:</strong>
  <%= c.title %>
</p>
<td><%= link_to homes_show_asigs_path,  :id => c.level.assignments.ids, class: " h" do %>
    <i class="glyphicon glyphicon-eye-open text-dark"></i> 
    <% end %>
<%end%>

<%= link_to 'Back', root_path %>