config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'homes#index'
  get 'homes/show_asigs'
  get 'homes/show'
  resources :submits
  resources :searches
  devise_for :users, controllers: {
    sessions: 'users/sessions'}
  resources :assignments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<% if current_user%>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  

<img src="/img/ur.png" style="height:15vh;">
     

   <li class="nav-item dropdown navbar-brand">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if current_user.admin%>
          

           Admin 

          <% else %>

          <%= current_user.first_name%>user

          <%end%>
        </a>
        
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          

          <%=link_to 'logout', destroy_user_session_path, method: :delete, class:'dropdown-item'%>

          <%=link_to 'Setting', edit_user_registration_path,  class:'dropdown-item'%>
 <% if current_user.admin%>
    <i class="glyphicon glyphicon-euro"></i> <%= link_to 'Dashboard', admin_root_path, class: "btn btn-default"  %>
         <%end%> 
        </div>
      </li>

      

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">


     <li class="nav-item active">
<%= link_to 'Home', root_path, class:'nav-link' %>
     </li>
      <li class="nav-item active">
        <% if current_user.admin %>
      <%= link_to 'New Assignment', new_assignment_path, class:'nav-link' %>

      <% else %>
    <%= link_to 'My Assignment', assignments_path, class:'nav-link' %>

      <% end %>
      </li>
      
    </ul>
   
  </div>
</nav>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SubApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
<%= render 'layouts/header' %>
  
  <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>


 